jenkins:
  # For Global CONF
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  numExecutors: 5
  scmCheckoutRetryCount: 2
  remotingSecurity:
    enabled: true

  # For Users
  securityRealm:
    local:
      allowsSignup: false 
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}

        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}

        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}

        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
    
#     # For Authorizations Strategy

  authorizationStrategy:
    roleBased:
      roles:
        global:
        # Global role for ADMIN
          - name: "admin"
            description: "Marvin master"
            permissions:
            - "Overall/Administer"
            assignments:  
            - "chocolateen"
       # Global role for APE
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Workspace"
            assignments:
              - "i_dont_know"
       # Global role for GORILLA
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
              - "Job/Workspace"
              - "Job/Create"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Move"
              - "Job/Cancel"
            assignments:
              - "vaugie_g"
       # Global role for ASSIST
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "nasso"

security:
  GlobalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
    - file: "job_dsl.groovy"